// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeobkruUQFU61TC_BuCDmOFzFIyChl0UQ',
    appId: '1:305778996481:web:72e679963867de5cfb9700',
    messagingSenderId: '305778996481',
    projectId: 'splitdumb-app2',
    authDomain: 'splitdumb-app2.firebaseapp.com',
    storageBucket: 'splitdumb-app2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotqA4upqiv_NnfQtbg5Rai6tlHRZQQ7U',
    appId: '1:305778996481:android:047aa34a9d61e46cfb9700',
    messagingSenderId: '305778996481',
    projectId: 'splitdumb-app2',
    storageBucket: 'splitdumb-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Y9TYauaM_O6W8ppY_7QyXax9Ap7Yw50',
    appId: '1:305778996481:ios:6e3a4bb3baf89838fb9700',
    messagingSenderId: '305778996481',
    projectId: 'splitdumb-app2',
    storageBucket: 'splitdumb-app2.firebasestorage.app',
    iosBundleId: 'com.splitdumb.splitdumb',
  );
}
